[env:esp32dev]
platform = espressif32@6.3.2
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	tzapu/WiFiManager
	bblanchon/ArduinoJson 
	Wire
	artronshop/IOXESP32_4-20mA_Receiver@^1.0.0
    knolleary/PubSubClient