name: Auto Build and Release ESP32

on:
  push:
    tags:
      - 'v*' 
  workflow_dispatch: # เพิ่มตัวนี้เพื่อกดรันเองได้

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: Run PlatformIO Build
        run: pio run

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: .pio/build/*/firmware.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# Updated at: 2026-04-22